name: Run Scraper Every 30 Minutes

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -e .

    - name: Install Microsoft Edge
      run: |
        sudo apt update
        sudo apt install -y microsoft-edge-stable

    - name: Download and install matching Edge WebDriver
      run: |
        echo "Getting Edge version..."
        FULL_EDGE_VERSION=$(microsoft-edge --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        if [ -z "$FULL_EDGE_VERSION" ]; then
          echo "Fetching precise version using LATEST_RELEASE..."
          BASE_VERSION=$(microsoft-edge --version | grep -oP '\d+\.\d+\.\d+')
          FULL_EDGE_VERSION=$(curl -s https://msedgedriver.azureedge.net/LATEST_RELEASE_$BASE_VERSION)
        fi
        echo "Edge version: $FULL_EDGE_VERSION"

        echo "Downloading matching Edge WebDriver..."
        wget -q "https://msedgedriver.azureedge.net/${FULL_EDGE_VERSION}/edgedriver_linux64.zip" -O edgedriver.zip
        unzip -q edgedriver.zip -d ./webdriver
        chmod +x ./webdriver/msedgedriver

        echo "Adding WebDriver to PATH..."
        export PATH=$PATH:$(pwd)/webdriver

    - name: Run scraper
      run: |
        source .venv/bin/activate
        python src/visa_scraping/ejecution.py
      env:
        USERNAME: ${{ secrets.SCRAPER_USERNAME }}
        PASSWORD: ${{ secrets.SCRAPER_PASSWORD }}
