name: Run Scraper Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies and set up WebDriver
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -e .

        wget -q https://msedgedriver.azureedge.net/113.0.1774.50/edgedriver_linux64.zip
        unzip -q edgedriver_linux64.zip -d ./webdriver
        chmod +x ./webdriver/msedgedriver

    - name: Install Microsoft Edge
      run: |
        sudo apt update
        sudo apt install -y microsoft-edge-stable

    - name: Debug installation
      run: |
        echo "Checking Microsoft Edge..."
        which microsoft-edge
        microsoft-edge --version
        echo "Checking WebDriver..."
        ./webdriver/msedgedriver --version

    - name: Run scraper
      run: |
        source .venv/bin/activate
        python src/visa_scraping/ejecution.py
      env:
        USERNAME: ${{ secrets.SCRAPER_USERNAME }}
        PASSWORD: ${{ secrets.SCRAPER_PASSWORD }}
