name: Run Scraper Every 60 Minutes

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 7-23 * * *" 
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -e .

    - name: Install Microsoft Edge
      run: |
        sudo apt update
        sudo apt install -y microsoft-edge-stable

    - name: Set execute permission on msedgedriver
      run: chmod +x ./src/visa_scraping/static/inputs/msedgedriver

    - name: Run scraper
      run: |
        source .venv/bin/activate
        python src/visa_scraping/ejecution.py
      env:
        USERNAME: ${{ secrets.SCRAPER_USERNAME }}
        PASSWORD: ${{ secrets.SCRAPER_PASSWORD }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        PASSWORD_EMAIL: ${{ secrets.PASSWORD_EMAIL }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
